// Generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DAside: typeof import('@no_idea/wind-ui')['DAside']
    DButton: typeof import('@no_idea/wind-ui')['DButton']
    DButtonGroup: typeof import('@no_idea/wind-ui')['DButtonGroup']
    DCol: typeof import('@no_idea/wind-ui')['DCol']
    DConfigProvider: typeof import('@no_idea/wind-ui')['DConfigProvider']
    DContainer: typeof import('@no_idea/wind-ui')['DContainer']
    DFooter: typeof import('@no_idea/wind-ui')['DFooter']
    DForm: typeof import('@no_idea/wind-ui')['DForm']
    DFormItem: typeof import('@no_idea/wind-ui')['DFormItem']
    DFormLabel: typeof import('@no_idea/wind-ui')['DFormLabel']
    DHeader: typeof import('@no_idea/wind-ui')['DHeader']
    DInput: typeof import('@no_idea/wind-ui')['DInput']
    DLink: typeof import('@no_idea/wind-ui')['DLink']
    DMain: typeof import('@no_idea/wind-ui')['DMain']
    DRow: typeof import('@no_idea/wind-ui')['DRow']
    DScrollbar: typeof import('@no_idea/wind-ui')['DScrollbar']
    DSpace: typeof import('@no_idea/wind-ui')['DSpace']
  }
}

export {}
